apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: istio-ingressgateway
  namespace: istio-gateway-ns-2
spec:
  listeners:
    - allowedRouteTables:
        - host: "*"
      http: {}
      port:
        number: 443
      tls:
        mode: SIMPLE
        secretName: test-secret
#    - http: {}
#      port:
#        number: 80
#      allowedRouteTables:
#        - host: "*"
  workloads:
    - selector:
        labels:
          istio: ingressgateway