apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: tracks-rt
  namespace: istio-gateway-ns
  labels:
    portal: dev-portal
    api: tracks
spec:
  hosts:
    - "*"
  portalMetadata:
    title: Catstronauts REST API V2
    description: REST API for Catstronauts to retrieve data for tracks, authors and modules.
    apiProductId: tracks-api-product
    apiVersion: v2
  http:
    - name: tracks-api
      labels:
#        usagePlans: devPortal no usage plans to apply to tracks api in cluster-2
      matchers:
        - uri:
            prefix: /trackapi
      forwardTo:
        pathRewrite: /
        destinations:
          - ref:
              name: tracks-rest-api
              namespace: tracks
              cluster: cluster-2
            port:
              number: 5000
  virtualGateways:
    - name: istio-ingressgateway
      namespace: istio-gateway-ns
      cluster: cluster-2