apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: istio-ingressgateway
  namespace: istio-gateway-ns
spec:
  listeners:
#    - allowedRouteTables:
#        - host: "*"
#      http: {}
#      port:
#        number: 443
#      tls:
#        mode: SIMPLE
#        secretName: test-secret
    - http: {}
      port:
        number: 80
      allowedRouteTables:
        - host: "api.petstore-2.com"
        - host: "api.tracks-2.com"
  workloads:
    - selector:
        labels:
          istio: ingressgateway